tap "dart-lang/dart"
tap "datawire/blackbird"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "adns"
brew "libpng"
brew "gettext"
brew "libssh2"
brew "aria2"
brew "libtool"
brew "asdf"
brew "gdbm"
brew "xz"
brew "python@3.10"
brew "awscli"
brew "azure-cli"
brew "blueutil"
brew "cabextract"
brew "libffi"
brew "pkg-config"
brew "pcre"
brew "ccat"
brew "cmake"
brew "docker-compose"
brew "emojify"
brew "libunistring"
brew "libtasn1"
brew "gnutls"
brew "ffmpeg"
brew "fish"
brew "mpfr"
brew "libmpc"
brew "gcc"
brew "geckodriver"
brew "git"
brew "git-lfs"
brew "libgpg-error"
brew "libassuan"
brew "libksba"
brew "libusb"
brew "npth"
brew "pinentry"
brew "gnupg"
brew "go"
brew "helm"
brew "hugo"
brew "jpeg"
brew "jq"
brew "json-c"
brew "kubernetes-cli"
brew "librdkafka"
brew "libusb-compat"
brew "mackup"
brew "mas"
brew "openjdk"
brew "maven"
brew "neofetch"
brew "node"
brew "nss"
brew "p7zip"
brew "pinentry-mac"
brew "postgresql@14"
brew "pv"
brew "python@3.9"
brew "ranger"
brew "ruby-build"
brew "rbenv"
brew "redis"
brew "ruby"
brew "telnet"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "wget"
brew "when"
brew "yarn"
brew "z"
brew "zsh"
brew "dart-lang/dart/dart"
cask "1password"
cask "adobe-acrobat-reader"
cask "agenda"
cask "alfred"
cask "arq"
cask "avast-security"
cask "bartender"
cask "battle-net"
cask "brave-browser"
cask "charles"
cask "cheatsheet"
cask "chromedriver"
cask "cyberduck"
cask "dash"
cask "datovka"
cask "devutils"
cask "disk-inventory-x"
cask "docker"
cask "dockstation"
cask "drawio"
cask "fantastical"
cask "firefox"
cask "flux"
cask "font-fira-code-nerd-font"
cask "gifcapture"
cask "gimp"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "google-drive-file-stream"
cask "handbrake"
cask "imageoptim"
cask "istat-menus"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "lens"
cask "macfuse"
cask "macvim"
cask "mark-text"
cask "microsoft-auto-update"
cask "microsoft-azure-storage-explorer"
cask "microsoft-edge"
cask "microsoft-office"
cask "microsoft-teams"
cask "nordlayer"
cask "nordvpn"
cask "parallels"
cask "parallels-access"
cask "parallels-toolbox"
cask "pdf-expert"
cask "postman"
cask "remarkable"
cask "rescuetime"
cask "screens"
cask "screens-connect"
cask "secure-pipes"
cask "sidequest"
cask "skype"
cask "slack"
cask "soapui"
cask "spotify"
cask "teamviewer"
cask "transmission"
cask "transmit"
cask "tripmode"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "vmware-horizon-client"
cask "webex-meetings"
cask "wireshark"
cask "wkhtmltopdf"
cask "zoom"
mas "1Password for Safari", id: 1569813296
mas "Bear", id: 1091189122
mas "CopyClip", id: 1020812363
mas "Disk Speed Test", id: 425264550
mas "Dynamo", id: 1445910651
mas "Endel", id: 1484348796
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Numbers", id: 409203825
mas "Okta Extension App", id: 1439967473
mas "Pages", id: 409201541
mas "Speedtest", id: 1153157709
mas "Termius", id: 1176074088
mas "Things", id: 904280696
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
